version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"  # Reduced frequency
    open-pull-requests-limit: 5  # Fewer concurrent PRs
    reviewers:
      - "tmaasen"
    assignees:
      - "tmaasen"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tmaasen"
    assignees:
      - "tmaasen"
    commit-message:
      prefix: "ci"
      include: "scope"